name: Lint Proto Frontend
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: Lint
        run: |
          cd proto
          npm install
          npm run lint
