name: Lint Proto Frontend
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: ./proto/scripts/run.sh npm run lint
